# Check out https://pre-commit.com/ for documentation
# and https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: 2.9.0
# Don't set language_version -- it's only useful if we have multiple
# python versions or our build uses a different env than runtime
repos:
  # --- Meta hooks ---
  #- hooks:
  # This one is useful, but it will fail if, e.g., you don't have a single yaml file
  #  - id: check-hooks-apply
  # This one will fail, e.g., if you don't have a recipes/ file, which is excluded here
  #   - id: check-useless-excludes
  #  repo: meta

  # --- Built-in hooks --
  - hooks:
      - id: check-symlinks
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-toml
      - id: check-json
      # This one is slow and doesn't check for much
      # - detect-private-key
      # This is very slow, so I recommend disabling it.
      #- id: check-added-large-files
      # The Conda recipe meta.yaml files are actually templates, not valid YAML
      - id: check-yaml
        exclude: ^recipes/.*
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0

  # --- Commit msg checks ---
  - hooks:
      - id: commitizen
        stages: ["commit-msg"]
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.14.0

  # --- Strip output from .ipynb files ---
  - hooks:
      - id: nbstripout
        files: ".ipynb"
    repo: https://github.com/kynan/nbstripout
    rev: master

  # --- Linters ---
  - hooks:
      - id: dockerfile_lint
    repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 20.8b1
  - repo: https://github.com/pre-commit/mirrors-prettier
    hooks:
      - id: prettier
    rev: v2.2.1
